safe: true
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
baseurl: /jp
url: https://www.jhipster.tech/jp
github_repository_url: https://github.com/jhipster/jp
kramdown:
  input: GFM
plugins:
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-redirect-from
  - jemoji
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
